site_name: Saffier
site_description: The only python ORM you will ever need.
site_url: https://saffier.tarsild.io

theme:
  name: "material"
  custom_dir: docs/overrides
  language: en
  palette:
    - scheme: "default"
      primary: "purple"
      accent: "amber"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "purple"
      accent: "amber"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  favicon: statics/images/favicon.ico
  logo: statics/images/logo-white.svg
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.code.select
    - navigation.indexes
    - navigation.path
    - navigation.tabs

repo_name: tarsil/saffier
repo_url: https://github.com/tarsil/saffier
edit_uri: ""
plugins:
  - search
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
      trim: false
  - markdownextradata:
      data: data
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            preload_modules: [databasez]
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

nav:
  - Home: "index.md"
  - Saffier: "saffier.md"
  - Core:
      - Models: "models.md"
      - Declarative Models: "declarative-models.md"
      - Reflection: "reflection.md"
      - Managers: "managers.md"
      - Fields: "fields.md"
      - Queries:
          - Queries: "queries/queries.md"
          - Related Name: "queries/related-name.md"
          - ManyToMany: "queries/many-to-many.md"
          - Prefetch Related: "queries/prefetch.md"
      - Transactions: "transactions.md"
  - Features:
      - Signals: "signals.md"
      - Relationships: "relationships.md"
      - Connection: "connection.md"
      - Tenancy:
          - Saffier: "tenancy/saffier.md"
          - Contrib: "tenancy/contrib.md"
      - Registry: "registry.md"
      - Shell Support: "shell.md"
      - Inspect DB: "inspectdb.md"
      - Migrations:
          - Discovery: "migrations/discovery.md"
          - Migrations: "migrations/migrations.md"
      - Settings: "settings.md"
  - Extras:
      - Exceptions: "exceptions.md"
      - Tips and Tricks: "tips-and-tricks.md"
      - Extras: "extras.md"
      - Test Client: "test-client.md"
  - API Reference:
      - "references/index.md"
      - Model: "references/models.md"
      - ReflectModel: "references/reflect-model.md"
      - Manager: "references/manager.md"
      - QuerySet: "references/queryset.md"
      - Signals: "references/signals.md"
      - Fields:
          - Field: "references/fields.md"
          - OneToOne: "references/one-to-one.md"
          - ForeignKey: "references/foreignkey.md"
          - ManyToMany: "references/many-to-many.md"
      - Registry: "references/registry.md"
      - Schema: "references/schemas.md"
      - Database: "references/database.md"
  - About:
      - Saffier People: "saffier-people.md"
      - Contributing: "contributing.md"
      - Sponsorship: "sponsorship.md"
  - Release Notes: "release-notes.md"
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - mdx_include:
      base_path: docs
  - admonition
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html

extra:
  alternate:
    - link: /
      name: English
      lang: en
    # - link: /pt/
    #   name: Portuguese (Portugal)
    #   lang: en

extra_css:
  - statics/css/extra.css
  - statics/css/custom.css
