site_name: Saffier
site_description: The only python ORM you will ever need.
site_url: https://saffier.tarsild.io

theme:
  name: "material"
  custom_dir: docs/overrides
  language: en
  palette:
    - scheme: "default"
      primary: "purple"
      accent: "amber"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "purple"
      accent: "amber"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  favicon: statics/images/favicon.ico
  logo: statics/images/logo-white.svg
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link

repo_name: tarsil/saffier
repo_url: https://github.com/tarsil/saffier
edit_uri: ""
plugins:
  - search
  - markdownextradata:
      data: data

nav:
  - Saffier: "index.md"
  - Models: "models.md"
  - Declarative Models: "declarative-models.md"
  - Reflection: "reflection.md"
  - Managers: "managers.md"
  - Fields: "fields.md"
  - Queries:
      - Queries: "queries/queries.md"
      - Related Name: "queries/related-name.md"
      - ManyToMany: "queries/many-to-many.md"
  - Transactions: "transactions.md"
  - Relationships: "relationships.md"
  - Connection: "connection.md"
  - Tenancy:
      - Saffier: "tenancy/saffier.md"
      - Contrib: "tenancy/contrib.md"
  - Registry: "registry.md"
  - Shell Support: "shell.md"
  - Settings: "settings.md"
  - Exceptions: "exceptions.md"
  - Migrations:
      - Discovery: "migrations/discovery.md"
      - Migrations: "migrations/migrations.md"
  - Tips and Tricks: "tips-and-tricks.md"
  - Extras: "extras.md"
  - Test Client: "test-client.md"
  - Saffier People: "saffier-people.md"
  - Contributing: "contributing.md"
  - Sponsorship: "sponsorship.md"
  - Release Notes: "release-notes.md"
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html

extra:
  alternate:
    - link: /
      name: English
      lang: en
    # - link: /pt/
    #   name: Portuguese (Portugal)
    #   lang: en

extra_css:
  - statics/css/extra.css
  - statics/css/custom.css
